export default {
  "hljs-comment": "        color: highlight;    ",
  "hljs-quote": "        color: highlight;    ",
  "hljs-variable": "  color: #d91e18;",
  "hljs-template-variable": "  color: #d91e18;",
  "hljs-tag": "  color: #d91e18;",
  "hljs-name": "  color: #d91e18;",
  "hljs-selector-id": "  color: #d91e18;",
  "hljs-selector-class": "  color: #d91e18;",
  "hljs-regexp": "  color: #d91e18;",
  "hljs-deletion": "  color: #d91e18;",
  "hljs-number": "        color: highlight;    ",
  "hljs-built_in": "        color: highlight;    ",
  "hljs-builtin-name": "        color: highlight;    ",
  "hljs-literal": "        color: highlight;    ",
  "hljs-type": "        color: highlight;    ",
  "hljs-params": "        color: highlight;    ",
  "hljs-meta": "        color: highlight;    ",
  "hljs-link": "        color: highlight;    ",
  "hljs-attribute": "        color: highlight;    ",
  "hljs-string": "        color: highlight;    ",
  "hljs-symbol": "        color: highlight;    ",
  "hljs-bullet": "        color: highlight;    ",
  "hljs-addition": "        color: highlight;    ",
  "hljs-title": "  color: #007faa;",
  "hljs-section": "  color: #007faa;",
  "hljs-keyword": "        font-weight: bold;    ",
  "hljs-selector-tag": "        font-weight: bold;    ",
  "hljs": "  display: block;  overflow-x: auto;  background: #fefefe;  color: #545454;  padding: 0.5em;",
  "hljs-emphasis": "  font-style: italic;",
  "hljs-strong": "  font-weight: bold;"
}