export default {
  "hljs": "  color: #363c69;",
  "hljs-keyword": "  font-weight: bold;",
  "hljs-selector-tag": "  font-weight: bold;",
  "hljs-literal": "  font-weight: bold;",
  "hljs-subst": "  color: #363c69;",
  "hljs-string": "  color: #2c009f;",
  "hljs-title": "  font-weight: bold;",
  "hljs-section": "  font-weight: bold;",
  "hljs-type": "  font-weight: bold;",
  "hljs-attribute": "  color: #2c009f;",
  "hljs-symbol": "  color: #2c009f;",
  "hljs-bullet": "  color: #2c009f;",
  "hljs-built_in": "  color: #2c009f;",
  "hljs-addition": "  color: #2c009f;",
  "hljs-variable": "  color: #2c009f;",
  "hljs-template-tag": "  color: #2c009f;",
  "hljs-template-variable": "  color: #2c009f;",
  "hljs-link": "  color: #2c009f;",
  "hljs-name": "  font-weight: bold;",
  "hljs-comment": "  color: #802022;",
  "hljs-quote": "  color: #802022;",
  "hljs-meta": "  color: #802022;",
  "hljs-deletion": "  color: #802022;",
  "hljs-doctag": "  font-weight: bold;",
  "hljs-strong": "  font-weight: bold;",
  "hljs-emphasis": "  font-style: italic;"
}