export default {
  "hljs": "  color: #f8f8f2;",
  "hljs-keyword": "  font-weight: bold;",
  "hljs-selector-tag": "  font-weight: bold;",
  "hljs-literal": "  font-weight: bold;",
  "hljs-section": "  font-weight: bold;",
  "hljs-link": "  color: #8be9fd;",
  "hljs-function .hljs-keyword": "  color: #ff79c6;",
  "hljs-subst": "  color: #f8f8f2;",
  "hljs-string": "  color: #f1fa8c;",
  "hljs-title": "  font-weight: bold;",
  "hljs-name": "  font-weight: bold;",
  "hljs-type": "  font-weight: bold;",
  "hljs-attribute": "  color: #f1fa8c;",
  "hljs-symbol": "  color: #f1fa8c;",
  "hljs-bullet": "  color: #f1fa8c;",
  "hljs-addition": "  color: #f1fa8c;",
  "hljs-variable": "  color: #f1fa8c;",
  "hljs-template-tag": "  color: #f1fa8c;",
  "hljs-template-variable": "  color: #f1fa8c;",
  "hljs-comment": "  color: #6272a4;",
  "hljs-quote": "  color: #6272a4;",
  "hljs-deletion": "  color: #6272a4;",
  "hljs-meta": "  color: #6272a4;",
  "hljs-doctag": "  font-weight: bold;",
  "hljs-strong": "  font-weight: bold;",
  "hljs-emphasis": "  font-style: italic;"
}