export default {
  "hljs": " /* Common set of rules required by highlight.js (don'r remove!) */\tdisplay: block;\toverflow-x: auto;\tpadding: 0.5em;\tbackground: #FFFFDF; /* Half and Half (approx.) *//* --- Uncomment to add PureBASIC native IDE styled font!\tfont-family: Consolas;*/",
  "hljs-name": "\tfont-weight: bold;",
  "hljs-number": "\tcolor: #000000; /* Black */",
  "hljs-attr": "\tcolor: #000000; /* Black */",
  "hljs-params": "\tcolor: #000000; /* Black */",
  "hljs-subst": "\tcolor: #000000; /* Black */",
  "hljs-regexp": "\tcolor: #00AAAA; /* Persian Green (approx.) */",
  "hljs-section": "\tcolor: #00AAAA; /* Persian Green (approx.) */",
  "hljs-selector-pseudo": "\tcolor: #00AAAA; /* Persian Green (approx.) */",
  "hljs-addition": "\tcolor: #00AAAA; /* Persian Green (approx.) */",
  "hljs-tag": "\tcolor: #006666; /* Blue Stone (approx.) */",
  "hljs-variable": "\tcolor: #006666; /* Blue Stone (approx.) */",
  "hljs-code": "\tcolor: #006666; /* Blue Stone (approx.) */",
  "hljs-class": "\tcolor: #006666; /* Blue Stone (approx.) */\tfont-weight: bold;",
  "hljs-meta-keyword": "\tcolor: #006666; /* Blue Stone (approx.) */\tfont-weight: bold;",
  "hljs-selector-class": "\tcolor: #006666; /* Blue Stone (approx.) */\tfont-weight: bold;",
  "hljs-built_in": "\tcolor: #006666; /* Blue Stone (approx.) */\tfont-weight: bold;",
  "hljs-builtin-name": "\tcolor: #006666; /* Blue Stone (approx.) */\tfont-weight: bold;",
  "hljs-selector-attr": "\tcolor: #0080FF; /* Azure Radiance (approx.) */",
  "hljs-link": "\tcolor: #924B72; /* Cannon Pink (approx.) */",
  "hljs-deletion": "\tcolor: #924B72; /* Cannon Pink (approx.) */",
  "hljs-attribute": "\tcolor: #924B72; /* Cannon Pink (approx.) */",
  "hljs-meta": "\tcolor: #924B72; /* Cannon Pink (approx.) */\tfont-weight: bold;",
  "hljs-literal": "\tcolor: #924B72; /* Cannon Pink (approx.) */\tfont-weight: bold;",
  "hljs-selector-id": "\tcolor: #924B72; /* Cannon Pink (approx.) */\tfont-weight: bold;",
  "hljs-strong": "\tfont-weight: bold;",
  "hljs-emphasis": "\tfont-style: italic;"
}