export default {
  "hljs": "  color: #3e5915;",
  "pre": "  background:#f6f6ae url(./school-book.png);  border-top: solid 2px #d2e8b9;  border-bottom: solid 1px #d2e8b9;",
  "hljs-keyword": "  font-weight: bold;",
  "hljs-selector-tag": "  font-weight: bold;",
  "hljs-literal": "  font-weight: bold;",
  "hljs-subst": "  color: #3e5915;",
  "hljs-string": "  color: #2c009f;",
  "hljs-title": "  font-weight: bold;",
  "hljs-section": "  font-weight: bold;",
  "hljs-type": "  font-weight: bold;",
  "hljs-symbol": "  color: #2c009f;",
  "hljs-bullet": "  color: #2c009f;",
  "hljs-attribute": "  color: #2c009f;",
  "hljs-built_in": "  color: #2c009f;",
  "hljs-builtin-name": "  color: #2c009f;",
  "hljs-addition": "  color: #2c009f;",
  "hljs-variable": "  color: #2c009f;",
  "hljs-template-tag": "  color: #2c009f;",
  "hljs-template-variable": "  color: #2c009f;",
  "hljs-link": "  color: #2c009f;",
  "hljs-comment": "  color: #e60415;",
  "hljs-quote": "  color: #e60415;",
  "hljs-deletion": "  color: #e60415;",
  "hljs-meta": "  color: #e60415;",
  "hljs-doctag": "  font-weight: bold;",
  "hljs-name": "  font-weight: bold;",
  "hljs-selector-id": "  font-weight: bold;",
  "hljs-strong": "  font-weight: bold;",
  "hljs-emphasis": "  font-style: italic;"
}